import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppsNavbar from "@/components/AppsNavbar";
import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";
import { createClient } from "../utils/supabase/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const supabase = createClient(cookieStore);
  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <div className="container mx-auto min-h-full">
            <AppsNavbar session={session} />
            {children}
            <div>this is will be the footer</div>
          </div>
        </AuthContext>
      </body>
    </html>
  );
}
